# Generated by Django 6.0.3 on 2026-04-01 17:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrobeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("top", "Góra"),
                            ("bottom", "Dół"),
                            ("dress", "Sukienki"),
                            ("shoes_acc", "Buty i Dodatki"),
                        ],
                        default="top",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
