# Generated by Django 6.0.3 on 2026-04-01 17:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('stylist', 'Stylist')], default='user', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('base', 'Base'), ('premium', 'Premium'), ('vip', 'VIP')], default='base', max_length=20)),
                ('used_stylist_reviews', models.IntegerField(default=0)),
                ('max_stylist_reviews', models.IntegerField(default=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52')], default='32', max_length=40)),
                ('height', models.PositiveIntegerField(default=160, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(220)])),
                ('body_type', models.CharField(choices=[('klepsydra', 'Klepsydra'), ('gruszka', 'Gruszka'), ('jablko', 'Jabłko'), ('prostokat', 'Prostokąt'), ('odwrocony_trojkat', 'Odwrócony Trójkąt')], default='klepsydra', max_length=40)),
                ('beauty_type', models.CharField(choices=[('jasna_wiosna', 'Jasna Wiosna'), ('prawdziwa_wiosna', 'Prawdziwa Wiosna'), ('zywa_wiosna', 'Żywa Wiosna'), ('jasne_lato', 'Jasne Lato'), ('prawdziwe_lato', 'Prawdziwe Lato'), ('miekkie_lato', 'Miękkie Lato'), ('miekka_jesien', 'Miękka Jesień'), ('prawdziwa_jesien', 'Prawdziwa Jesień'), ('gleboka_jesien', 'Głęboka Jesień'), ('gleboka_zima', 'Głęboka Zima'), ('prawdziwa_zima', 'Prawdziwa Zima'), ('jasna_zima', 'Jasna Zima')], default='jasne_lato', max_length=40)),
                ('style_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('favourite_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
