# Generated by Django 6.0.3 on 2026-04-01 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_category', models.CharField(max_length=100)),
                ('code_string', models.CharField(max_length=100)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('is_vip_only', models.BooleanField(default=True)),
            ],
        ),
    ]
