name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  PYTHON_VERSION: '3.14.2'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Tests


    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-mock pytest-cov

      - name: Test with coverage
        run: pytest --cov tests

